Add a Job of Ansible to the CI

diff --git a/.github/workflows/tf.yml b/.github/workflows/tf.yml
--- a/.github/workflows/tf.yml
+++ b/.github/workflows/tf.yml
@@ -66,19 +66,29 @@ jobs:
       - name: Capture Terraform Outputs
         id: capture-outputs
         run: |
-          TF_IPS=$(terraform output -json instance_public_ips | jq -r '. | join(",")')
-          echo "TF_IPS=$TF_IPS" >> $GITHUB_ENV
+          IP_JSON=$(terraform output -json instance_public_ips)
+          echo "IP_JSON is: $IP_JSON"
+          
+          # Safely parse JSON and join array elements into a string
+          if echo "$IP_JSON" | jq empty; then
+            TF_IPS=$(echo "$IP_JSON" | jq -r '. | join(",")')
+            echo "TF_IPS=$TF_IPS" >> $GITHUB_ENV
+          else
+            echo "Failed to parse JSON"
+            exit 1
+          fi
+      
           echo "TF_DYNAMODB_TABLE=$(terraform output -raw dynamodb_name)" >> $GITHUB_ENV
           echo "TF_SQS_URL=$(terraform output -raw sqs_url)" >> $GITHUB_ENV
           echo "TF_S3_NAME=$(terraform output -raw s3_name)" >> $GITHUB_ENV
           echo "TF_ALB_URL=$(terraform output -raw alb_url)" >> $GITHUB_ENV
-          
-    outputs:
-      ips: ${{ steps.capture-outputs.outputs.TF_IPS }}
-      dynamodb_table_name: ${{ steps.capture-outputs.outputs.TF_DYNAMODB_TABLE }}
-      sqs_queue_name: ${{ steps.capture-outputs.outputs.TF_SQS_URL }}
-      s3_bucket_name: ${{ steps.capture-outputs.outputs.TF_S3_NAME }}
-      alb_url: ${{ steps.capture-outputs.outputs.TF_ALB_URL }}
+                
+          outputs:
+            ips: ${{ steps.capture-outputs.outputs.TF_IPS }}
+            dynamodb_table_name: ${{ steps.capture-outputs.outputs.TF_DYNAMODB_TABLE }}
+            sqs_queue_name: ${{ steps.capture-outputs.outputs.TF_SQS_URL }}
+            s3_bucket_name: ${{ steps.capture-outputs.outputs.TF_S3_NAME }}
+            alb_url: ${{ steps.capture-outputs.outputs.TF_ALB_URL }}
   
     
   Ansible:
